[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "SCVdb"
authors = [{name = "Zhengmin Yu", email = "yuzmbio@163.com"}]
dynamic = ["version", "description"]
